### PR TITLE
all pattern matching ops on ChargingPointType now cover all cases

### LINKED ISSUE #1940: Cover new and old ChargingPointTypes in all match statements
10:45:49.912 [ClusterSystem-akka.actor.default-dispatcher-226] ERROR akka.actor.OneForOneStrategy - invalid argument: Level1
java.lang.IllegalArgumentException: invalid argument: Level1

This error was experienced due to the fact that the `ChargingPointType` class constructor and the functions on ChargingPointType do not cover all cases that exist.

This task is to fully cover all defined types in all cases where `ChargingPointType` is pattern-matched.

### PR DESCRIPTION
**Pull request by robfitzgerald**
errors were occurring because the legacy `ChargingPointType`s were not properly "cased out" in pattern matching over `ChargingPointType` values.

i also modified the ChargingPointType Regex so that it is "unanchored" and can grab occurrences of the named charging point from a row at any position. that is consistent with the design, but, now that i'm thinking about it, if a user used a reserved ChargingPointType or PricingModel name in their TAZ name, then the regex would find that. maybe we should restrict our parsing to the row/column instead of the entire row.

anyhow, this fixes the bug. perhaps additionally we should add test class(es) for the charging code. 

Closes #1940.

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/1941)

### CODE REVIEW

File: src/main/scala/beam/agentsim/infrastructure/charging/ChargingPointType.scala [hunk 1]
```diff
@@ -99,6 +99,12 @@ object ChargingPointType {
       case ChargingStationCcsComboType2 => 50
       case TeslaSuperCharger            => 135
       case CustomChargingPoint(_, v, _) => v
+      // legacy charging points (values taken from 2018 BEAM code)
```
Comment (robfitzgerald) [inline src/main/scala/beam/agentsim/infrastructure/charging/ChargingPointType.scala]: @johanneshiry plz double-check the values i put in place for the legacy types, if you don't mind - both AC/DC and the KwH. i just grabbed them from the old implementation. i think it should work as expected.

**Comment by REASY** [comment]
@robfitzgerald there is [scala formatiing failure:](https://beam-ci.tk/job/beam-forced-prs/1405/console)
```
23:10:19 :checkScalafmt FAILED
```
Could you please apply formatting? Thanks!

**Comment by rjf-nrel** [comment]
test!

**Comment by robfitzgerald** [comment]
@REASY @johanneshiry if you would be so kind to review, that would be rad :pray:

File: src/main/scala/beam/agentsim/infrastructure/charging/ChargingPointType.scala (hunk 1 above)
Comment (johanneshiry) [reply src/main/scala/beam/agentsim/infrastructure/charging/ChargingPointType.scala]: The "worse" thing about the old definitions is, that Level1 / Level2 Charging rate are not fixed defined but more of a range of installed charging capacity. Anyway the values you picked are in range or close to the definitions of Level1/2 charging. So we can keep them for now until the personal ev branch will be merged in.

File: src/main/scala/beam/agentsim/infrastructure/charging/ChargingPointType.scala [hunk 2]
```diff
@@ -116,7 +122,13 @@ object ChargingPointType {
       case ChargingStationCcsComboType2 => DC
       case TeslaSuperCharger            => DC
       case CustomChargingPoint(_, _, c) => c
-      case _                            => throw new IllegalArgumentException("invalid argument")
+      // legacy charging points
+      case Level2    => AC
+      case Level1    => AC
+      case DCFast    => DC
+      case UltraFast => DC
+      case NoCharger => AC
```
Comment (johanneshiry) [inline src/main/scala/beam/agentsim/infrastructure/charging/ChargingPointType.scala]: doesn't make sense as a call on NoCharger should throw an IllegalArgumentException but we can keep this anyway for now to make it work.
