### PR TITLE
[Issue-3058] Update akka http version and fix here adapter 4ci

### LINKED ISSUE #3058: Update Akka http version and fix here api when there is only one span

### PR DESCRIPTION
**Pull request by carloscaldas**
Closes #3058 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3059)

### CODE REVIEW

File: src/main/scala/beam/utils/mapsapi/hereapi/HereService.scala [hunk 1]
```diff
@@ -40,16 +36,17 @@ class HereService(adapter: HereAdapter) {
...
         }
       }
   }
 
-  case class TmpSpan(startIndex: Int, endIndex: Int, lengthInMeters: Int, speedLimitInKph: Option[Int])
+  case class TmpSpan(startIndex: Int, endIndex: Int, lengthInMeters: Int, speedLimitInMetersPerSecond: Option[Int])
 }
 
 object HereService {
+  private val hereTimeout: Duration = Duration("15 seconds")
```
Comment (JustinPihony) [inline src/main/scala/beam/utils/mapsapi/hereapi/HereService.scala:49]: Why bump from 5 sec to 15 seconds?

**Review by JustinPihony — APPROVED** [review]
Just one minor question

File: src/main/scala/beam/utils/mapsapi/hereapi/HereService.scala (hunk 1 above)
Comment (carloscaldas) [reply src/main/scala/beam/utils/mapsapi/hereapi/HereService.scala:49]: it is possible to do batch queries. just o be "sure" it will not get timeout errors
