### PR TITLE
Fixed messages for ComparingUnrelatedTypes

### LINKED ISSUE #2991: Scapegoat - remove TryGet,EitherGet and Comparing Unrelated Type error messages
Related to #2985

### PR DESCRIPTION
**Pull request by carloscaldas**
Closes #2991

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3202)

### CODE REVIEW

File: src/main/scala/beam/sim/BeamMobsim.scala [hunk 1]
```diff
@@ -194,7 +194,7 @@ class BeamMobsim @Inject()(
       val modesAvailable: List[BeamMode] = nonCavModesAvailable ++ cavModeAvailable
 
       persons.foreach { person =>
-        if (matsimServices.getIterationNumber == 0) {
+        if (matsimServices.getIterationNumber.intValue() == 0) {
```
Comment (dimaopen) [inline src/main/scala/beam/sim/BeamMobsim.scala:197]: If we don't use this .intValue() then a warning is produced? This decreases readability a little.

File: build.gradle [hunk 2]
```diff
@@ -335,7 +335,7 @@ tasks.withType(ScalaCompile) {
         def additionalParameters = ["-Xplugin:" + configurations.scalaCompilerPlugin.asPath,
                                     "-P:scapegoat:dataDir:" + buildDir + "/reports/scapegoat",
                                     "-P:scapegoat:reports:html:xml",
-                                    "-P:scapegoat:disabledInspections:OptionGet:UnsafeTraversableMethods:ComparingUnrelatedTypes:TryGet:EitherGet",
+                                    "-P:scapegoat:disabledInspections:OptionGet:UnsafeTraversableMethods:TryGet:EitherGet:AsInstanceOf:NullAssignment:UnusedMethodParameter:VariableShadowing:NullParameter:MethodReturningAny:IsInstanceOf:EmptyIfBlock:CatchException:EmptyInterpolatedString:UnnecessaryConversion:CatchThrowable:CollectionIndexOnNonIndexedSeq:AvoidSizeNotEqualsZero:ComparingFloatingPointTypes:UnsafeContains:VarCouldBeVal:CatchThrowable:ParameterlessMethodReturnsUnit:SuspiciousMatchOnClassObject:PointlessTypeBounds:BrokenOddness:VarClosure:EmptyTryBlock:RepeatedIfElseBody:BigDecimalDoubleConstructor:EmptyInterpolatedString:SwallowedException:LooksLikeInterpolatedString",
```
Comment (JustinPihony) [inline build.gradle:338]: You added a bunch, but removed `ComparingUnrelatedTypes`. Is there a reason for that?

File: src/main/scala/beam/calibration/BeamSigoptTuner.scala [hunk 3]
```diff
@@ -38,7 +38,8 @@ object BeamSigoptTuner {
     val experimentList = Experiment.list().call().getData
     val optExperiment = experimentList.stream
       .filter(
-        (experiment: Experiment) => experiment.getId == experimentId & experiment.getDevelopment == development
+        (experiment: Experiment) =>
+          experiment.getId == experimentId && experiment.getDevelopment.booleanValue() == development
```
Comment (JustinPihony) [inline src/main/scala/beam/calibration/BeamSigoptTuner.scala:42]: `booleanValue()` seems repetitive - was there a reason?

File: src/main/scala/beam/sim/BeamMobsim.scala (hunk 1 above)
Comment (carloscaldas) [reply src/main/scala/beam/sim/BeamMobsim.scala:197]: @dimaopen scapegoat gets lost because `getIterationNumber` returns `java.lang.Integer` and `intValue` returns `int` which it considered the same as scala `Int`. So, this is needed in order to avoid warning

File: src/main/scala/beam/router/r5/RouteDumper.scala [hunk 4]
```diff
@@ -487,6 +487,7 @@ object RouteDumper {
     Schema.createRecord("routingRequest", "", "", false, fields.asJava)
   }
 
+  @SuppressWarnings(Array("ComparingUnrelatedTypes"))
```
[the remark this answers is not in the document]
Comment (carloscaldas) [reply src/main/scala/beam/router/r5/RouteDumper.scala:490]: @dimaopen this happens because of the line `case x if x == classTag[String] =>`

[the remark this answers is not in the document]
Comment (carloscaldas) [reply src/main/scala/beam/router/r5/RouteDumper.scala:490]: The problem is the line `x if x == classTag[String] =>` I will replace with `x if Objects.equals(x, classTag[String])`

File: src/main/scala/beam/sim/BeamMobsim.scala (hunk 1 above)
Comment (carloscaldas) [reply src/main/scala/beam/sim/BeamMobsim.scala:197]: Options I can see:
```Scala
matsimServices.getIterationNumber.intValue() == 0
```
or
```Scala
matsimServices.getIterationNumber == java.lang.Integer.valueOf(0)
```
or
```Scala
val ZERO = java.lang.Integer.valueOf(0)
...
matsimServices.getIterationNumber == ZERO
```
or
```Scala
Objects.equals(matsimServices.getIterationNumber, 0)
```
or
```Scala
0.equals(matsimServices.getIterationNumber)
```

File: src/main/scala/beam/utils/data/ctpp/JointDistribution.scala [hunk 5]
```diff
@@ -88,9 +87,9 @@ class JointDistribution(
       new CPair[Map[String, String], java.lang.Double](row(value, sampleWithinRange), value(RETURN_COLUMN).toDouble)
     }.toVector
 
-    val values = pmf.map(_.getValue)
-    if (values.isEmpty || values.reduce(_ + _) == 0.0) {
-      return Map()
+    val values = pmf.map(_.getValue.doubleValue())
```
Comment (JustinPihony) [inline src/main/scala/beam/utils/data/ctpp/JointDistribution.scala:90]: Another slot where the express value call seems duplicative.

File: build.gradle (hunk 2 above)
Comment (carloscaldas) [reply build.gradle:338]: @JustinPihony yes, because ComparingUnrelatedTypes is what this PR is solving. So no need to disable it anymore

File: src/main/scala/beam/utils/data/ctpp/JointDistribution.scala (hunk 5 above)
Comment (carloscaldas) [reply src/main/scala/beam/utils/data/ctpp/JointDistribution.scala:90]: @JustinPihony pls check explanation above

File: src/main/scala/beam/calibration/BeamSigoptTuner.scala (hunk 3 above)
Comment (carloscaldas) [reply src/main/scala/beam/calibration/BeamSigoptTuner.scala:42]: @JustinPihony please check explanation above

File: src/main/scala/beam/router/r5/RouteDumper.scala (hunk 4 above)
[the remark this answers is not in the document]
Comment (JustinPihony) [reply src/main/scala/beam/router/r5/RouteDumper.scala]: Interesting that these are subtly different if you look at the source, which is what is flagged.

File: build.gradle (hunk 2 above)
Comment (JustinPihony) [reply build.gradle]: Ahh, I misread that.

File: src/main/scala/beam/sim/BeamMobsim.scala (hunk 1 above)
Comment (JustinPihony) [reply src/main/scala/beam/sim/BeamMobsim.scala:197]: I think the last one is best here 0.equals...

Comment (JustinPihony) [reply src/main/scala/beam/sim/BeamMobsim.scala:197]: But it is more of a preference - so nbd either way

**Review by JustinPihony — APPROVED** [review]

**Comment by JustinPihony** [comment]
Changing the version somehow is messing with the scala version or something of that sort it seems

> 01:40:03 Caused by: java.lang.NoSuchMethodError: scala.tools.nsc.Global.reporter()Lscala/tools/nsc/reporters/Reporter;
> 01:40:03 	at com.sksamuel.scapegoat.ScapegoatComponent$$anon$1.run(plugin.scala:207)

**Comment by JustinPihony** [comment]
Test!

**Comment by carloscaldas** [comment]
Test now!

**Comment by JustinPihony** [comment]
Same error as previously reported.

**Comment by JustinPihony** [comment]
All good now - the version of 2.12.12 was supported, but I think something else was pulling in 13, so bumping to that fixed things
