### PR TITLE
Zip routing output results for each step

### LINKED ISSUE #2762: CCH: Compress the files
Austin run with CCH has stuck, it has error:
```
07:35:45.475 [main] ERROR o.m.c.c.MatsimRuntimeModifications - Getting uncaught Exception in Thread main
org.supercsv.exception.SuperCsvException: the nameMapping array and the sourceList should be the same size (nameMapping length = 6, sourceList size = 3)
	at org.supercsv.util.Util.filterListToMap(Util.java:125)
	at org.supercsv.io.CsvMapReader.read(CsvMapReader.java:79)
	at beam.physsim.cchRoutingAssignment.DockerRoutingFrameworkWrapper.$anonfun$assignTrafficAndFetchWay2TravelTime$3(RoutingFrameworkWrapper.scala:189)
	at scala.collection.Iterator$$anon$9.next(Iterator.scala:173)
	at scala.collection.Iterator$$anon$15.hasNext(Iterator.scala:656)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at beam.physsim.cchRoutingAssignment.DockerRoutingFrameworkWrapper.$anonfun$assignTrafficAndFetchWay2TravelTime$2(RoutingFrameworkWrapper.scala:202)
	at beam.physsim.cchRoutingAssignment.DockerRoutingFrameworkWrapper.$anonfun$assignTrafficAndFetchWay2TravelTime$2$adapted(RoutingFrameworkWrapper.scala:186)
	at beam.utils.CloseableUtil$RichCloseable$.use$extension(CloseableUtil.scala:9)
	at beam.physsim.cchRoutingAssignment.DockerRoutingFrameworkWrapper.assignTrafficAndFetchWay2TravelTime(RoutingFrameworkWrapper.scala:186)
	at beam.physsim.cchRoutingAssignment.RoutingFrameworkTravelTimeCalculator.$anonfun$generateLink2TravelTimes$5(RoutingFrameworkTravelTimeCalculator.scala:99)
	at beam.physsim.cchRoutingAssignment.RoutingFrameworkTravelTimeCalculator.$anonfun$generateLink2TravelTimes$5$adapted(RoutingFrameworkTravelTimeCalculator.scala:93)
	at scala.collection.immutable.List.map(List.scala:290)
	at beam.physsim.cchRoutingAssignment.RoutingFrameworkTravelTimeCalculator.generateLink2TravelTimes(RoutingFrameworkTravelTimeCalculator.scala:93)
	at beam.physsim.jdeqsim.AgentSimToPhysSimPlanConverter.setupActorsAndRunPhysSim(AgentSimToPhysSimPlanConverter.java:192)
	at beam.physsim.jdeqsim.AgentSimToPhysSimPlanConverter.startPhysSim(AgentSimToPhysSimPlanConverter.java:470)
	at beam.sim.BeamSim.$anonfun$notifyIterationEnds$13(BeamSim.scala:373)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
07:35:45.475 [main] ERROR o.m.c.c.MatsimRuntimeModifications - ERROR --- This is an unexpected shutdown!
```
CCH csv files are not compressed which takes a lot of disk space:
image

### PR DESCRIPTION
**Pull request by crixal**
Resolves #2762 

This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/2779)

### CODE REVIEW

**Comment by crixal** [comment]
Test!

File: src/main/scala/beam/utils/FileUtils.scala [hunk 1]
```diff
@@ -337,4 +338,21 @@ object FileUtils extends LazyLogging {
...
     Await.result(Future.sequence(futures), atMost)
   }
+
+  def gzipFile(file: String, deleteSourceFile: Boolean = false): Unit = {
+    val filePath = Paths.get(file)
+    if (!filePath.toFile.isFile) {
+      throw new IllegalStateException(s"Not a file: `$file`")
+    }
+
+    using(IOUtils.getBufferedWriter(file, true)) { bw =>
```
Comment (JustinPihony) [inline src/main/scala/beam/utils/FileUtils.scala:348]: It took me a lot of time to understand how this worked because the true was not indicative of how this turns into a gzip. For future readability I would suggest to use the named argument:

```suggestion
    using(IOUtils.getBufferedWriter(file, useCompression = true)) { bw =>
```

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test now!
