### PR TITLE
FIx None Value of trip_id

### LINKED ISSUE #3368: Include activitysim trip_id as attribute in BEAM plans
Right now the BEAM urbansim/activitysim csv inputs have a trip_id column. Can we find a way to read this in and store it as a trip attribute that can be output in our plans and some relevant events (mode choice, PersonEntersVehicle, etc.)?

image

### PR DESCRIPTION
**Pull request by Xuan-1998**
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3425)

### CODE REVIEW

**Comment by Xuan-1998** [comment]
Test!

**Comment by Xuan-1998** [comment]
Test!

File: src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala [hunk 1]
```diff
@@ -565,13 +565,27 @@ class UrbanSimScenarioLoader(
           planInfo.legMode match {
             case Some(mode) =>
               val leg = PopulationUtils.createLeg(mode)
-              leg.getAttributes.putAttribute("trip_id", planInfo.tripId)
+
+              if (planInfo.tripId != null) {
```
Comment (JustinPihony) [inline src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala]: You can embed this:

```
leg.getAttributes.putAttribute("trip_id", if(planInfo.tripId != null) planInfo.tripId else "")
```

or (more terse, but more objects for GC)

```
leg.getAttributes.putAttribute("trip_id", Option(planInfo.tripId).getOrElse(""))
```

Comment (JustinPihony) [reply src/main/scala/beam/utils/scenario/UrbanSimScenarioLoader.scala]: Or since it is all off of `tripId`, then you could move it outside of the match to be used in a single place:

```
val tripId = //whichever path to set - if/else or Option
..
//use stored tripId directly
```

**Review by JustinPihony — APPROVED** [review]
Stylistic suggestions more than anything, bit more scala-esque than java-esque.

**Comment by Xuan-1998** [comment]
Test!
