### PR TITLE
Tests: flaky tests 3324 - Added withRetries and WithFixture with at …

### LINKED ISSUE #3324: Tests: flaky tests
We have a bunch of tests that from time to time not working.
We need to investigate the possible reasons behind this and make them more stable.
One of solutions - create a trait that will lead the flaky tests to rerun a number of times.

Here are links with related information:
https://gist.github.com/dwickern/6ba9c5c505d2325d3737ace059302922
https://stackoverflow.com/questions/22799495/scalatest-running-a-test-50-times

Some of flaky tests:

- `beam.integration.ChargingSpec`
- `beam.integration.CAVSpec`
- `beam.agentsim.infrastructure.ChargingNetworkManagerSpec`

### PR DESCRIPTION
**Pull request by norberto108**
Added withRetries and WithFixture with at least 5 retries

- - -
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3599)

### CODE REVIEW

File: src/test/scala/beam/integration/CAVSpec.scala [hunk 1]
```diff
@@ -94,4 +96,31 @@ class CAVSpec extends AnyFlatSpec with Matchers with BeamHelper {
...
+        } else
+          withFixture(test, count - 1)
+      case Canceled(_) =>
+        if (count > 0) {
+          super.withFixture(test)
+        } else
+          withFixture(test, count - 1)
+      case other => other
+    }
+  }
```
Comment (nikolayilyin) [inline src/test/scala/beam/integration/CAVSpec.scala]: I would rewrite this like that:

  def withFixture(test: NoArgTest, count: Int): Outcome = {
    val outcome = super.withFixture(test)
    println(outcome.toString)
    outcome match {
      case Failed(_) if count==1 => super.withFixture(test)
      case Failed(_) =>	             withFixture(test, count - 1)
      case Canceled(_) if count ==1 => super.withFixture(test)
       case Canceled(_) =>                    withFixture(test, count - 1)
      case other => other
    }
  }

**Review by nikolayilyin — COMMENTED** [review]
Looks good.
Could you, please, provide an example of output for changed tests in case they were retried?

File: src/test/scala/beam/agentsim/infrastructure/ChargingNetworkManagerSpec.scala [hunk 2]
```diff
@@ -483,4 +485,34 @@ class ChargingNetworkManagerSpec
...
+        } else
+          withFixture(test, count - 1)
+      case Canceled(_) =>
+        if (count > 0) {
+          super.withFixture(test)
+        } else
+          withFixture(test, count - 1)
+      case other => other
+    }
+  }
```
Comment (nikolayilyin) [inline src/test/scala/beam/agentsim/infrastructure/ChargingNetworkManagerSpec.scala]: It would be a good idea to put these methods in a trait to avoid repetitive code

**Comment by norberto108** [comment]
@nikolayilyin Accordingly with our conversation on Slack. I copied the result from a 5 retries because there is a forced error in the test.

`assert( 1 equals 2, "Forced error")`




```
Testing started at 14:12 ...





14:12:26.373 [ClusterSystem-akka.actor.default-dispatcher-12] ERROR b.a.a.h.HouseholdFleetManager - [1] THE LIST OF VEHICLES SHOULD NOT BE EMPTY
Failed(org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced error)
14:12:49.710 [ClusterSystem-akka.actor.default-dispatcher-12] ERROR b.a.a.h.HouseholdFleetManager - [1] THE LIST OF VEHICLES SHOULD NOT BE EMPTY
Failed(org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced error)
14:13:01.828 [ClusterSystem-akka.actor.default-dispatcher-6] ERROR b.a.a.h.HouseholdFleetManager - [1] THE LIST OF VEHICLES SHOULD NOT BE EMPTY
Failed(org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced error)
14:13:12.504 [ClusterSystem-akka.actor.default-dispatcher-7] ERROR b.a.a.h.HouseholdFleetManager - [1] THE LIST OF VEHICLES SHOULD NOT BE EMPTY
Failed(org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced error)
14:13:23.696 [ClusterSystem-akka.actor.default-dispatcher-7] ERROR b.a.a.h.HouseholdFleetManager - [1] THE LIST OF VEHICLES SHOULD NOT BE EMPTY
Failed(org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced error)
14:13:34.902 [ClusterSystem-akka.actor.default-dispatcher-12] ERROR b.a.a.h.HouseholdFleetManager - [1] THE LIST OF VEHICLES SHOULD NOT BE EMPTY


1.equals(2) was false Forced error
ScalaTestFailureLocation: beam.integration.ChargingSpec at (ChargingSpec.scala:219)
org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced error
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
	at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
	at beam.integration.ChargingSpec.$anonfun$new$1(ChargingSpec.scala:219)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1812)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at beam.integration.ChargingSpec.beam$integration$Repeated$$super$withFixture(ChargingSpec.scala:31)
	at beam.integration.Repeated.withFixture(Repeated.scala:25)
	at beam.integration.Repeated.withFixture$(Repeated.scala:21)
	at beam.integration.ChargingSpec.withFixture(ChargingSpec.scala:31)
	at beam.integration.Repeated.withFixture(Repeated.scala:25)
	at beam.integration.Repeated.withFixture$(Repeated.scala:21)
	at beam.integration.ChargingSpec.withFixture(ChargingSpec.scala:31)
	at beam.integration.Repeated.withFixture(Repeated.scala:25)
	at beam.integration.Repeated.withFixture$(Repeated.scala:21)
	at beam.integration.ChargingSpec.withFixture(ChargingSpec.scala:31)
	at beam.integration.Repeated.withFixture(Repeated.scala:25)
	at beam.integration.Repeated.withFixture$(Repeated.scala:21)
	at beam.integration.ChargingSpec.withFixture(ChargingSpec.scala:31)
	at beam.integration.Repeated.withFixture(Repeated.scala:25)
	at beam.integration.Repeated.withFixture$(Repeated.scala:21)
	at beam.integration.ChargingSpec.withFixture(ChargingSpec.scala:31)
	at beam.integration.Repeated.withFixture(Repeated.scala:16)
	at beam.integration.Repeated.withFixture$(Repeated.scala:14)
	at beam.integration.ChargingSpec.withFixture(ChargingSpec.scala:31)
	at org.scalatest.flatspec.AnyFlatSpecLike.invokeWithFixture$1(AnyFlatSpecLike.scala:1810)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTest$1(AnyFlatSpecLike.scala:1822)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest(AnyFlatSpecLike.scala:1822)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTest$(AnyFlatSpecLike.scala:1804)
	at org.scalatest.flatspec.AnyFlatSpec.runTest(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$runTests$1(AnyFlatSpecLike.scala:1880)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:413)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:427)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:475)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests(AnyFlatSpecLike.scala:1880)
	at org.scalatest.flatspec.AnyFlatSpecLike.runTests$(AnyFlatSpecLike.scala:1879)
	at org.scalatest.flatspec.AnyFlatSpec.runTests(AnyFlatSpec.scala:1685)
	at org.scalatest.Suite.run(Suite.scala:1112)
	at org.scalatest.Suite.run$(Suite.scala:1094)
	at org.scalatest.flatspec.AnyFlatSpec.org$scalatest$flatspec$AnyFlatSpecLike$$super$run(AnyFlatSpec.scala:1685)
	at org.scalatest.flatspec.AnyFlatSpecLike.$anonfun$run$1(AnyFlatSpecLike.scala:1925)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:535)
	at org.scalatest.flatspec.AnyFlatSpecLike.run(AnyFlatSpecLike.scala:1925)
	at org.scalatest.flatspec.AnyFlatSpecLike.run$(AnyFlatSpecLike.scala:1923)
	at org.scalatest.flatspec.AnyFlatSpec.run(AnyFlatSpec.scala:1685)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13(Runner.scala:1322)
	at org.scalatest.tools.Runner$.$anonfun$doRunRunRunDaDoRunRun$13$adapted(Runner.scala:1316)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1316)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24(Runner.scala:993)
	at org.scalatest.tools.Runner$.$anonfun$runOptionallyWithPassFailReporter$24$adapted(Runner.scala:971)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1482)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:971)
	at org.scalatest.tools.Runner$.run(Runner.scala:798)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2or3(ScalaTestRunner.java:43)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:26)



Process finished with exit code 0

````

**Comment by norberto108** [comment]
The classes that extends from **AnyFlatSpec** uses **Repeated** trait, the other classes are inheriting from **TestKit** needs a different approach

File: src/test/scala/beam/integration/Repeated.scala [hunk 3]
```diff
@@ -0,0 +1,28 @@
+package beam.integration
+
+import beam.sim.BeamHelper
+import org.scalatest._
+import org.scalatest.flatspec.AnyFlatSpec
+import org.scalatest.matchers.should.Matchers
+
+
+trait Repeated extends AnyFlatSpec with Matchers with BeamHelper with Retries {
```
Comment (nikolayilyin) [inline src/test/scala/beam/integration/Repeated.scala]: Why it should extend so many traits?

File: src/test/scala/beam/integration/ParkingSpec.scala [hunk 4]
```diff
@@ -238,4 +241,20 @@ class ParkingSpec
...
+  }
+
+  def withFixture(test: NoArgTest, count: Int): Outcome = {
+    val outcome = super.withFixture(test)
+    println(outcome.toString)
+    outcome match {
+      case Failed(_) | Canceled(_) => if (count == 1) super.withFixture(test) else withFixture(test, count - 1)
+      case other => other
+    }
+  }
```
Comment (nikolayilyin) [inline src/test/scala/beam/integration/ParkingSpec.scala]: these method looks pretty identical to the method of Repeated trait, why we can't extend this trait here and avoid code duplication?

File: src/test/scala/beam/agentsim/infrastructure/ChargingNetworkManagerSpec.scala [hunk 5]
```diff
@@ -483,4 +487,23 @@ class ChargingNetworkManagerSpec
...
+
+  def withFixture(test: NoArgTest, count: Int): Outcome = {
+    val outcome = super.withFixture(test)
+    println(outcome.toString)
+    outcome match {
+      case Failed(_) | Canceled(_) => if (count == 1) super.withFixture(test) else withFixture(test, count - 1)
+      case other => other
+    }
+  }
```
Comment (nikolayilyin) [inline src/test/scala/beam/agentsim/infrastructure/ChargingNetworkManagerSpec.scala]: the same question about code duplication

File: src/test/scala/beam/integration/ParkingSpec.scala (hunk 4 above)
Comment (norberto108) [reply src/test/scala/beam/integration/ParkingSpec.scala]: I was not able to extend Repeated trait because this class doesn't match AnyFlatSpec, i was wanting to do a POC. I am going to simplify removing AnyFlatSpec from the Repeated trait, i think it will work.

File: src/test/scala/beam/agentsim/infrastructure/ChargingNetworkManagerSpec.scala (hunk 5 above)
Comment (norberto108) [reply src/test/scala/beam/agentsim/infrastructure/ChargingNetworkManagerSpec.scala]: i am working on it. Please check previous comment

**Comment by norberto108** [comment]
Five retries before fail in ChargingNetworkManagerSpec

`assert( 1 equals 2, "Forced" )
`
```
[DEBUG] [08/25/2022 09:19:48.042] [ChargingNetworkManagerSpec-scheduler-1] [akka://ChargingNetworkManagerSpec/user/$$b] timeSpentToPlanEnergyDispatchTrigger: 0 ms, nHandledPlanEnergyDispatchTrigger: 0, AVG: NaN
[DEBUG] [08/25/2022 09:19:48.056] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] Planning energy dispatch for vehicles currently connected to a charging point, at t=0
[DEBUG] [08/25/2022 09:19:48.182] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] timeSpentToPlanEnergyDispatchTrigger: 126. tick: 0
Failed(org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced)
[DEBUG] [08/25/2022 09:19:56.789] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] Planning energy dispatch for vehicles currently connected to a charging point, at t=0
[DEBUG] [08/25/2022 09:19:56.809] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] timeSpentToPlanEnergyDispatchTrigger: 146. tick: 0
Failed(org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced)
[DEBUG] [08/25/2022 09:19:57.013] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] Planning energy dispatch for vehicles currently connected to a charging point, at t=0
[DEBUG] [08/25/2022 09:19:57.033] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] timeSpentToPlanEnergyDispatchTrigger: 166. tick: 0
Failed(org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced)
[DEBUG] [08/25/2022 09:19:57.237] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] Planning energy dispatch for vehicles currently connected to a charging point, at t=0
[DEBUG] [08/25/2022 09:19:57.259] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] timeSpentToPlanEnergyDispatchTrigger: 188. tick: 0
Failed(org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced)
[DEBUG] [08/25/2022 09:19:57.463] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] Planning energy dispatch for vehicles currently connected to a charging point, at t=0
[DEBUG] [08/25/2022 09:19:57.483] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] timeSpentToPlanEnergyDispatchTrigger: 208. tick: 0
Failed(org.scalatest.exceptions.TestFailedException: 1.equals(2) was false Forced)
[DEBUG] [08/25/2022 09:19:57.687] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] Planning energy dispatch for vehicles currently connected to a charging point, at t=0
[DEBUG] [08/25/2022 09:19:57.707] [ScalaTest-run-running-ChargingNetworkManagerSpec] [akka://ChargingNetworkManagerSpec/user/$$b] timeSpentToPlanEnergyDispatchTrigger: 228. tick: 0
[DEBUG] [08/25/2022 09:20:19.266] [ChargingNetworkManagerSpec-scheduler-1] [akka://ChargingNetworkManagerSpec/user/$$b] timeSpentToPlanEnergyDispatchTrigger: 228 ms, nHandledPlanEnergyDispatchTrigger: 6, AVG: 38.0


1.equals(2) was false Forced
ScalaTestFailureLocation: beam.agentsim.infrastructure.ChargingNetworkManagerSpec at (ChargingNetworkManagerSpec.scala:166)

```

**Review by nikolayilyin — APPROVED** [review]
lgtm

**Comment by nikolayilyin** [comment]
test!

**Comment by norberto108** [comment]
test!
