### PR TITLE
fix reading of .osm files generated from .xml

### LINKED ISSUE #3199: R5 not running on network converted from XML
The TSCORE users are having trouble running BEAM on a network that was converted from a MATSIM .xml using our utility. It looks like the network isn't being successfully built as routable in BEAM.

I'm pretty sure this is happening because R5 assumes a link isn't routable if it doesn't have the "highway" tag. I think all we have to do is write the tag "highway" = the "type" field from the matsim .xml input here:

https://github.com/LBNL-UCB-STI/beam/blob/5e06bb252b9a6ebc2ebd9454b7d0394c49f32b63/src/test/scala/beam/router/PhyssymXmlToOsmConverter.scala#L124-L132

### PR DESCRIPTION
**Pull request by zneedell**
R5 requires this tag in order to add a link to the roadNetwork

Resolves #3199

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/3200)

### CODE REVIEW

**Review by JustinPihony — APPROVED** [review]

**Comment by JustinPihony** [comment]
test!

**Comment by JustinPihony** [comment]
test!

File: src/test/scala/beam/router/PhyssymXmlToOsmConverter.scala [hunk 1]
```diff
@@ -288,6 +290,11 @@ object PhyssymXmlToOsmConverter extends StrictLogging {
     osmWay
   }
 
+  private def metersPerSecondToKilometersPerHour(speed: String): String = {
+    val output = try { speed.toDouble * 3.6 } catch { case _: Throwable => DEFAULT_LINK_SPEED_KPH }
```
Comment (JustinPihony) [inline src/test/scala/beam/router/PhyssymXmlToOsmConverter.scala:294]: Since you aren't logging the exception, you can do:

`scala.util.Try(speed.toDouble * 3.6).getOrElse(DEFAULT_LINK_SPEED_KPH).toString`

**Review by JustinPihony — APPROVED** [review]

**Review by PresideMoon — APPROVED** [review]

**Comment by JustinPihony** [comment]
@zneedell Is this ready to be merged?

**Comment by zneedell** [comment]
Yep, thanks!
