### PR TITLE
report error if config not found

### LINKED ISSUE #721: if config file not found report that as error, instead of ConfigException
e.g. Caused by: com.typesafe.config.ConfigException$Missing: No configuration setting found for key

### PR DESCRIPTION
**Pull request by zishanbilal**
fixed #721

---
This change is [Reviewable](https://reviewable.io/reviews/lbnl-ucb-sti/beam/772)

### CODE REVIEW

File: src/main/scala/beam/sim/BeamHelper.scala [hunk 1]
```diff
@@ -237,7 +237,7 @@ trait BeamHelper extends LazyLogging {
     }
     assert(
       !isConfigArgRequired || (isConfigArgRequired && parsedArgs.config.isDefined),
-      "config is a required value, and must yield a valid config."
+      "Beam config is a required, must provide a valid configuration file."
```
Comment (JustinPihony) [inline src/main/scala/beam/sim/BeamHelper.scala]: Can you change to "..., please provide a valid..." or "..., you must provide..." or ", a valid configuration file must be provided.".

And in fact, while we are improving it, let's help a bit more and add an example:

> Beam config is required.... For example:
>  ./gradlew :run -PappArgs="['--config', 'test/input/beamville/beam.conf']"
